### ISSUE TITLE
Slope of a Line

### ISSUE THREAD

**Issue by Kyle-P** [Kyle-P/Mathematics#13]
Create a program to find the slope of a line given two points on the line. The program should go under the [Algebra folder](https://github.com/Kyle-P/Mathematics/tree/master/Algebra). Title the program SlopeOfALine.java.

Refer to the [quadratic formula code](https://github.com/Kyle-P/Mathematics/blob/master/Algebra/QuadraticFormula.java) to find out how to prompt users for data and use it accordingly.

**Comment by agawish** [comment]
Hi @Kyle-P,
Just created a pull-request for this.
