### ISSUE TITLE
Heron's Area Explanation

### ISSUE THREAD

**Issue by Kyle-P** [Kyle-P/Mathematics#9]
Please add an explanation to users for how the the area of the inputted triangle computed in 
[Heron's Area Calculator](https://github.com/Kyle-P/Mathematics/blob/master/Geometry/Heron.java).

Remember that each program must explain to users how answers are generated rather than just providing an answer.

**Comment by kira0992** [comment]
Hi,
I can take this up. Could you point me to some explanation in the project, so I get a general idea about the explanation template?

**Comment by Kyle-P** [comment]
Hi @kira0992! That'd be great!

For the explanation, just display to the user the necessary steps to calculate the right answer. For example, you could display Heron's Area Formula, display the formula with the numbers plugged in, and show the steps to solve. As long as you display the formula in some way that looks nice and is easy to understand, you should be fine. It might be helpful to put yourself in the user's position and ask yourself if you would understand how the answer was computed based on what the program is outputting.

Hope this helps! If you have any other questions, feel free to ask.
